@startuml Containers
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_TOP_DOWN()
LAYOUT_WITH_LEGEND()
AddContainerTag("database", $bgColor="#9ACD32", $fontColor="black")
AddContainerTag("integration", $bgColor="#FFD700", $fontColor="black")
Person(engineer, "Разработчик")

Container_Boundary(platform, "IoT Platform") {
    Container(api, "API Gateway", "Spring cloud gateway", "Маршрутизация и авторизация")
    Container(device_service, "Device Service", "Spring Boot", "CRUD API по устройствам. Использует встроенное шардирование через JDBC")
    Container(event_service, "Event Service", "Spring Boot", "Чтение данных из  Cassandra")
    Container(command_service, "Command Service", "GO + gRPC", "Принимает команды по gRPC и отдает их устройствам. Работает с отдельной БД PostgresSQL")
    Container("ev_collector", Events Collector,"Spring Boot", "Вычитывает и транспортирует телемтрию")
    Container("dev_collector", Device Collector,"Spring Boot", "Вычитывает и транспортирует информацию об усмтройстве")
    ContainerDb(pg_devices, "PostgreSQL (Devices)", "Rel Database", "Шардированная БД устройств. Синхронная репликация каждого шарда.", $tags="database")
    ContainerDb(pg_command, "PostgreSQL (Commands)", "Rel Database", "Отдельная БД для команд. Использукется GO-сервисовм.", $tags="database")
    ContainerDb(cassandra, "Cassandra", "NoSQL Database", "Хранилище телеметрии", $tags="database")
    ContainerQueue(queue, "Kafka", "Message Broker", "Очередь сообщений для событий", $tags="integration")
    Container(cache, "Redis", "In-Memory Cache", "Кэширование запросов")
    Container(minio, "MinIO", "Object Storage", "Сохранение ошибок DLT")
    Container(dlt, "Failed Events Processor", "Spring Boot", "DLT -> JSON -> MinIO")
    Container(orchestrator, "API Orchestrator", "Spring Boot", "Оркестратор: вызывает сервисы: command, event, device")
    System_Ext(ext_auth, "Keycloak", "Аутентификация и авторизация", "SSO/OAuth2 сервер")
}

System_Ext(ext_device, "IoT-устройство", "Отправляют телеметрию и получают команды")
Rel(ext_device, queue, "Публикация сообщений (producer)", "Kafka protocol")
Rel(api, ext_auth, "OAuth2 запрос токена", "HTTP/JSON")
Rel(api, orchestrator, "REST", "JWT")
Rel(orchestrator, event_service, "REST")
Rel(orchestrator, device_service, "REST")
Rel(orchestrator, command_service, "gRPC")
Rel(command_service, ext_device, "gRPC")
Rel(command_service, pg_command, "JDBC")
Rel(dlt, queue, "DLT topic (consumer)", "Kafka protocol")
Rel(dlt, minio, "Загрузка JSON с ошибками", "JSON")
Rel(queue, device_service, "Подписка на сообщения (consumer)", "Kafka protocol")
Rel(device_service, queue, "Чтение данных от устройств (consumer)", "Kafka")
Rel(device_service, pg_devices, "Чтение данных об устройствах", "JDBC")
Rel(orchestrator, cache, "Кэширование")
Rel(event_service, cassandra, "Чтение данных", "CQL")
Rel(engineer, api, "Мониторинг процессов", "HTTP (Camunda Cockpit)")
Rel(queue, ev_collector, "Подписка на события (consumer)")
Rel(ev_collector, cassandra, "Транспортировка сырых сообщений")
Rel_Down(queue, dev_collector, "Подписка на события (consumer)")
Rel(dev_collector, pg_devices, "Сохранение информации об устройствах", "JDBC")
@enduml